version: 2
# Tell CircleCI to use this workflow
workflows:
  version: 2
  default:
    jobs:
      - "python-3.6"
      - "python-3.7"
      - "python-3.8"
      - "linting"

default-job: &default-job
  docker:
    - image: continuumio/miniconda3:latest
  steps:
    - checkout
    - restore_cache:
        key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_JOB }}
    - run:
        name: Install conda environment
        command: ./ci/install-circle.sh
    - run:
        name: Running checks
        command: ./ci/${TEST_SCRIPT}
    - save_cache:
        key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Environment.CIRCLE_JOB }}
        paths:
          - "/opt/conda/envs/${ENV_NAME}/"
          - "/opt/conda/pkgs"


jobs:
  "python-3.6":
    <<: *default-job
    environment:
      PYTHON: "3.6"
      ENV_NAME: "pop-tools-dev"
      TEST_SCRIPT: "run-checks.sh"

  "python-3.7":
    <<: *default-job
    environment:
      PYTHON: "3.7"
      ENV_NAME: "pop-tools-dev"
      TEST_SCRIPT: "run-checks.sh"

  "python-3.8":
    <<: *default-job
    environment:
      PYTHON: "3.8"
      ENV_NAME: "pop-tools-dev"
      TEST_SCRIPT: "run-checks.sh"

  "linting":
    <<: *default-job
    environment:
      PYTHON: "3.7"
      ENV_NAME: "pop-tools-dev"
      TEST_SCRIPT: "run-linter.sh"
