version: 2
# Tell CircleCI to use this workflow
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
  default:
    jobs:
      - "upstream-dev"
      - "python-3.6"
      - "python-3.7"

shared: &shared
  steps:
    - checkout
    - restore_cache:
        key: deps-{{ checksum "./ci/environment.yml" }}
    - run:
        name: Install conda environment
        command: |
          conda env update -n base -f ${ENV_FILE}
          conda list
    - run:
        name: Running Tests
        command: |
          pytest --junitxml=test-reports/junit.xml --cov=./ --verbose
          codecov
    - save_cache:
        key: deps-{{ checksum "./ci/environment.yml" }}
        paths:
          - "/opt/conda/pkgs"


jobs:
  "upstream-dev":
    <<: *shared
    docker:
      - image: ncarxdev/miniconda:3.7
    environment:
      ENV_FILE: "./ci/environment-upstream-dev.yml"

  "python-3.6":
    <<: *shared
    docker:
      - image: ncarxdev/miniconda:3.6
    environment:
      ENV_FILE: "./ci/environment.yml"

  "python-3.7":
    <<: *shared
    docker:
      - image: ncarxdev/miniconda:3.7
    environment:
      ENV_FILE: "./ci/environment.yml"
