version: 2
# Tell CircleCI to use this workflow
workflows:
  version: 2
  default:
    jobs:
      - "upstream-dev"
      - "linting"

default-job: &default-job
  docker:
    - image: continuumio/miniconda3:latest
  steps:
    - checkout
    - restore_cache:
        key: deps-{{ checksum "./ci/environment.yml" }}
    - run:
        name: Install conda environment
        command: ./ci/install-circle.sh
    - run:
        name: Running checks
        command: ./ci/${TEST_SCRIPT}
    - save_cache:
        key: deps-{{ checksum "./ci/environment.yml" }}
        paths:
          - "/opt/conda/envs/${ENV_NAME}/"
          - "/opt/conda/pkgs"


jobs:
  "upstream-dev":
    docker:
      - image: continuumio/miniconda3:latest
    environment:
      ENV_NAME: "pop-tools-dev"
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "./ci/environment.yml" }}
      - run:
          name: Install conda environment
          command: |
            conda config --set always_yes true --set changeps1 false
            conda env update -f ci/environment-upstream-dev.yml
            source activate ${ENV_NAME}
            python -m pip install --no-deps -e .
            conda list -n ${ENV_NAME}
      - run:
          name: Running Tests
          command: |
             source activate ${ENV_NAME}
             pytest --junitxml=test-reports/junit.xml --cov=./ --verbose
      - save_cache:
          key: deps-{{ checksum "./ci/environment.yml" }}
          paths:
            - "/opt/conda/envs/${ENV_NAME}/"
            - "/opt/conda/pkgs"

  "linting":
    <<: *default-job
    environment:
      PYTHON: "3.7"
      ENV_NAME: "pop-tools-dev"
      TEST_SCRIPT: "run-linter.sh"
