name: pop-tools-dev
channels:
  - conda-forge
dependencies:
  - autopep8
  - black
  - bottleneck
  - codecov
  - dask
  - flake8
  - isort
  - jupyterlab
  - make
  - matplotlib
  - nbsphinx
  - netcdf4
  - numba
  - numpy
  - numpydoc
  - pip
  - pytest
  - pytest-cov
  - python=3.7
  - recommonmark
  - scipy
  - sphinx_rtd_theme=0.4.2
  - sphinx=1.8.2
  - xarray>=0.12
  - zarr
  - docrep
  - pytest-lazy-fixture
  - pytest-xdist
  - sphinx-copybutton
  - pip:
    - git+https://github.com/NCAR/aletheia-data.git#egg=aletheia-data
