name: pop-tools-dev
channels:
  - conda-forge
dependencies:
  - autopep8
  - black
  - bottleneck
  - codecov
  - flake8
  - isort
  - jupyterlab
  - make
  - matplotlib
  - nbsphinx
  - netcdf4
  - numba
  - numpydoc
  - pip
  - pytest
  - pytest-cov
  - pytest-lazy-fixture
  - pytest-xdist
  - python=3.7
  - recommonmark
  - scipy
  - sphinx_rtd_theme=0.4.2
  - sphinx-copybutton
  - sphinx=1.8.2
  - xgcm
  - zarr
