name: pop-tools-dev
channels:
  - conda-forge
dependencies:
  - autopep8
  - black
  - bottleneck
  - codecov
  - dask
  - docrep
  - flake8
  - isort
  - jupyterlab
  - matplotlib
  - nbsphinx
  - netcdf4
  - numba
  - numpy
  - numpydoc
  - pip
  - pooch>=0.7.0
  - pytest
  - pytest-cov
  - pytest-lazy-fixture
  - pytest-xdist
  - recommonmark
  - scipy
  - sphinx_rtd_theme
  - sphinx-copybutton
  - sphinx
  - watermark
  - xarray>=0.12
  - zarr
