name: pop-tools-dev
channels:
  - conda-forge
  - conda_build_test
dependencies:
  - bottleneck
  - codecov
  - dask
  - distributed
  - git
  - jupyterlab
  - matplotlib
  - netcdf4
  - numba
  - numpy
  - pip
  - pytest
  - pytest-cov
  - python=3.6
  - scipy
  - xarray>=0.12
  - svn
  - pip:
    - docrep
    - pytest-lazy-fixture
    - pytest-xdist
