name: pop-tools-dev
channels:
  - conda-forge
dependencies:
  - bottleneck
  - codecov
  - jupyterlab
  - matplotlib
  - netcdf4
  - numba
  - pip
  - pytest
  - pytest-cov
  - pytest-lazy-fixture
  - pytest-xdist
  - python=3.6
  - scipy
  - zarr
  - docrep
  - pytest-lazy-fixture
  - pytest-xdist
  - pooch
  - watermark
  - pip:
      - git+https://github.com/xgcm/xgcm.git
