name: pop-tools-dev
channels:
  - conda-forge
dependencies:
  - bottleneck
  - codecov
  - docrep
  - nbsphinx
  - numba
  - pip
  - pooch
  - pytest-cov
  - pyyaml
  - scipy
  - pip:
      - git+https://github.com/xgcm/xgcm.git
