name: pop-tools-dev
channels:
  - conda-forge
dependencies:
  - bottleneck
  - codecov
  - dask
  - docrep
  - nbsphinx
  - netcdf4
  - numba
  - pip
  - pooch
  - pytest
  - pytest-cov
  - pytest-lazy-fixture
  - pytest-xdist
  - python=3.7
  - pyyaml
  - scipy
  - zarr
  - pip:
      - git+https://github.com/xgcm/xgcm.git
      - git+https://github.com/pydata/xarray.git
      - git+https://github.com/dask/dask.git
