name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  checks:
    name: Black Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Black Code Formatter
        uses: lgeiger/black-action@master
        with:
          args: ". --line-length 100 --skip-string-normalization"
